import type { Config } from 'tailwindcss'
const { nextui } = require('@nextui-org/react')

export default {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
        './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        screens: {
            sm: '480px',
            md: '768px',
            lg: '976px',
            xl: '1440px',
        },
        fontFamily: {
            display: '"Afacad Flux", "Poppins", ui-sans',
        },
        extend: {
            spacing: {
                '128': '32rem',
                '144': '36rem',
            },
            borderRadius: {
                '4xl': '2rem',
            },
        },
    },
    darkMode: 'class',
    plugins: [
        nextui({
            themes: {
                light: {
                    colors: {
                        default: {
                            '50': '#fafafa',
                            '100': '#f2f2f3',
                            '200': '#ebebec',
                            '300': '#e3e3e6',
                            '400': '#dcdcdf',
                            '500': '#d4d4d8',
                            '600': '#afafb2',
                            '700': '#8a8a8c',
                            '800': '#656567',
                            '900': '#404041',
                            foreground: '#000',
                            DEFAULT: '#d4d4d8',
                        },
                        primary: {
                            '50': '#fefefe',
                            '100': '#fdfbfb',
                            '200': '#fcf9f9',
                            '300': '#fbf7f7',
                            '400': '#faf5f5',
                            '500': '#f9f3f3',
                            '600': '#cdc8c8',
                            '700': '#a29e9e',
                            '800': '#767373',
                            '900': '#4b4949',
                            foreground: '#000',
                            DEFAULT: '#f9f3f3',
                        },
                        secondary: {
                            '50': '#e4e4e4',
                            '100': '#bebfbe',
                            '200': '#989998',
                            '300': '#727373',
                            '400': '#4c4e4d',
                            '500': '#262827',
                            '600': '#1f2120',
                            '700': '#191a19',
                            '800': '#121313',
                            '900': '#0b0c0c',
                            foreground: '#fff',
                            DEFAULT: '#262827',
                        },
                        success: {
                            '50': '#e5f3e8',
                            '100': '#c0e3c7',
                            '200': '#9cd3a7',
                            '300': '#77c386',
                            '400': '#53b266',
                            '500': '#2ea245',
                            '600': '#268639',
                            '700': '#1e692d',
                            '800': '#164d21',
                            '900': '#0e3115',
                            foreground: '#000',
                            DEFAULT: '#2ea245',
                        },
                        warning: {
                            '50': '#fef4e4',
                            '100': '#fce4bd',
                            '200': '#fad497',
                            '300': '#f9c571',
                            '400': '#f7b54a',
                            '500': '#f5a524',
                            '600': '#ca881e',
                            '700': '#9f6b17',
                            '800': '#744e11',
                            '900': '#4a320b',
                            foreground: '#000',
                            DEFAULT: '#f5a524',
                        },
                        danger: {
                            '50': '#fce2eb',
                            '100': '#f8b9cf',
                            '200': '#f390b3',
                            '300': '#ef6796',
                            '400': '#ea3e7a',
                            '500': '#e6155e',
                            '600': '#be114e',
                            '700': '#960e3d',
                            '800': '#6d0a2d',
                            '900': '#45061c',
                            foreground: '#000',
                            DEFAULT: '#e6155e',
                        },
                        background: '#ffffff',
                        foreground: {
                            '50': '#dfdfdf',
                            '100': '#b3b3b3',
                            '200': '#868686',
                            '300': '#595959',
                            '400': '#2d2d2d',
                            '500': '#000000',
                            '600': '#000000',
                            '700': '#000000',
                            '800': '#000000',
                            '900': '#000000',
                            foreground: '#fff',
                            DEFAULT: '#000000',
                        },
                        content1: {
                            DEFAULT: '#ffffff',
                            foreground: '#000',
                        },
                        content2: {
                            DEFAULT: '#f4f4f5',
                            foreground: '#000',
                        },
                        content3: {
                            DEFAULT: '#e4e4e7',
                            foreground: '#000',
                        },
                        content4: {
                            DEFAULT: '#d4d4d8',
                            foreground: '#000',
                        },
                        focus: '#647384',
                        overlay: '#000000',
                        divider: '#111111',
                    },
                },
                dark: {
                    colors: {
                        default: {
                            '50': '#141417',
                            '100': '#232327',
                            '200': '#313136',
                            '300': '#3f3f46',
                            '400': '#6a6a70',
                            '500': '#959599',
                            '600': '#c1c1c3',
                            '700': '#ececed',
                            foreground: '#fff',
                            DEFAULT: '#313136',
                        },
                        primary: {
                            '50': '#514f4f',
                            '100': '#898686',
                            '200': '#c1bcbc',
                            '300': '#f9f3f3',
                            '400': '#faf6f6',
                            '500': '#fcf8f8',
                            '600': '#fdfbfb',
                            '700': '#fefefe',
                            foreground: '#000',
                            DEFAULT: '#c1bcbc',
                        },
                        secondary: {
                            '50': '#0c0d0d',
                            '100': '#151615',
                            '200': '#1d1f1e',
                            '300': '#262827',
                            '400': '#575858',
                            '500': '#888988',
                            '600': '#b8b9b9',
                            '700': '#e9eae9',
                            foreground: '#fff',
                            DEFAULT: '#1d1f1e',
                        },
                        success: {
                            '50': '#0f3516',
                            '100': '#195926',
                            '200': '#247e35',
                            '300': '#2ea245',
                            '400': '#5db76f',
                            '500': '#8ccc99',
                            '600': '#bbe1c3',
                            '700': '#eaf6ec',
                            foreground: '#fff',
                            DEFAULT: '#247e35',
                        },
                        warning: {
                            '50': '#50360c',
                            '100': '#875b14',
                            '200': '#be801c',
                            '300': '#f5a524',
                            '400': '#f7b955',
                            '500': '#face87',
                            '600': '#fce2b8',
                            '700': '#fef6e9',
                            foreground: '#000',
                            DEFAULT: '#be801c',
                        },
                        danger: {
                            '50': '#4b071f',
                            '100': '#7f0c34',
                            '200': '#b21049',
                            '300': '#e6155e',
                            '400': '#ec4a82',
                            '500': '#f17ea6',
                            '600': '#f7b3cb',
                            '700': '#fde8ef',
                            foreground: '#fff',
                            DEFAULT: '#b21049',
                        },
                        background: '#000000',
                        foreground: {
                            '50': '#535353',
                            '100': '#8c8c8c',
                            '200': '#c6c6c6',
                            '300': '#ffffff',
                            '400': '#ffffff',
                            '500': '#ffffff',
                            '600': '#ffffff',
                            '700': '#ffffff',
                            foreground: '#000',
                            DEFAULT: '#c6c6c6',
                        },
                        content1: {
                            DEFAULT: '#18181b',
                            foreground: '#fff',
                        },
                        content2: {
                            DEFAULT: '#27272a',
                            foreground: '#fff',
                        },
                        content3: {
                            DEFAULT: '#3f3f46',
                            foreground: '#fff',
                        },
                        content4: {
                            DEFAULT: '#52525b',
                            foreground: '#fff',
                        },
                        focus: '#647384',
                        overlay: '#ffffff',
                        divider: '#ffffff',
                    },
                },
            },
            layout: {
                fontSize: {
                    tiny: '0.875rem',
                    small: '1rem',
                    medium: '1.125rem',
                    large: '1.15rem',
                },
                lineHeight: {
                    tiny: '1.25rem',
                    small: '1.5rem',
                    medium: '1.75rem',
                    large: '2rem',
                },
                radius: {
                    small: '0.25rem',
                    medium: '0.5rem',
                    large: '0.75rem',
                },
                borderWidth: {
                    small: '1.5px',
                    medium: '2.5px',
                    large: '3.5px',
                },
                disabledOpacity: '0.5',
                dividerWeight: '1',
                hoverOpacity: '0.9',
            },
        }),
    ],
} satisfies Config
