import type { Config } from 'tailwindcss'
const { heroui } = require('@heroui/react')

export default {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
        './src/experiences/**/*.{js,ts,jsx,tsx,mdx}',
        './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        screens: {
            sm: '480px',
            md: '768px',
            lg: '976px',
            xl: '1440px',
            '2xl': '3840px',
        },
        fontFamily: {
            display: '"Afacad Flux", "Source Code Pro", ui-sans',
        },
        extend: {
            spacing: {
                '128': '32rem',
                '144': '36rem',
            },
            borderRadius: {
                '4xl': '2rem',
            },
            borderColor: {
                '50': '#fafafa',
                '100': '#f2f2f3',
                '200': '#ebebec',
                '300': '#e3e3e6',
                '400': '#dcdcdf',
                '500': '#d4d4d8',
                '600': '#afafb2',
                '700': '#8a8a8c',
                '800': '#656567',
                '900': '#404041',
            },
        },
    },
    darkMode: 'class',
    plugins: [
        heroui({
            themes: {
                light: {
                    colors: {
                        default: {
                            '50': '#f8f7f2', // Eggshell white
                            '100': '#f2f0e6',
                            '200': '#e8e4d9',
                            '300': '#dfd9cc',
                            '400': '#d5cebf',
                            '500': '#cbc3b2',
                            '600': '#b0a99a',
                            '700': '#968f83',
                            '800': '#7c766c',
                            '900': '#625e55',
                            foreground: '#3a3730',
                        },
                        primary: {
                            '50': '#f0f9ff',
                            '100': '#e0f2fe',
                            '200': '#bae6fd',
                            '300': '#7dd3fc',
                            '400': '#38bdf8',
                            '500': '#0ea5e9',
                            '600': '#0284c7',
                            '700': '#0369a1',
                            '800': '#075985',
                            '900': '#0c4a6e',
                            foreground: '#fff',
                        },
                        secondary: {
                            '50': '#fdf4ff',
                            '100': '#fae8ff',
                            '200': '#f5d0fe',
                            '300': '#f0abfc',
                            '400': '#e879f9',
                            '500': '#d946ef',
                            '600': '#c026d3',
                            '700': '#a21caf',
                            '800': '#86198f',
                            '900': '#701a75',
                            foreground: '#fff',
                        },
                        focus: '#00563B', // Updated focus color to match primary
                        background: '#f8f7f2', // Eggshell white
                        foreground: '#3a3730', // Warm dark brown
                        overlay: '#00000010',
                        divider: '#e8e4d9',
                        content1: {
                            DEFAULT: '#f2f0e6',
                            foreground: '#3a3730',
                        },
                        content2: {
                            DEFAULT: '#e8e4d9',
                            foreground: '#3a3730',
                        },
                        content3: {
                            DEFAULT: '#dfd9cc',
                            foreground: '#3a3730',
                        },
                        content4: {
                            DEFAULT: '#d5cebf',
                            foreground: '#3a3730',
                        },
                    },
                },
                dark: {
                    colors: {
                        default: {
                            '50': '#141417',
                            '100': '#232327',
                            '200': '#313136',
                            '300': '#3f3f46',
                            '400': '#6a6a70',
                            '500': '#959599',
                            '600': '#c1c1c3',
                            '700': '#ececed',
                            foreground: '#fff',
                            DEFAULT: '#313136',
                        },
                        primary: {
                            '50': '#514f4f',
                            '100': '#898686',
                            '200': '#c1bcbc',
                            '300': '#f9f3f3',
                            '400': '#faf6f6',
                            '500': '#fcf8f8',
                            '600': '#fdfbfb',
                            '700': '#fefefe',
                            foreground: '#000',
                            DEFAULT: '#c1bcbc',
                        },
                        secondary: {
                            '50': '#0c0d0d',
                            '100': '#151615',
                            '200': '#1d1f1e',
                            '300': '#262827',
                            '400': '#575858',
                            '500': '#888988',
                            '600': '#b8b9b9',
                            '700': '#e9eae9',
                            foreground: '#fff',
                            DEFAULT: '#1d1f1e',
                        },
                        success: {
                            '50': '#0f3516',
                            '100': '#195926',
                            '200': '#247e35',
                            '300': '#2ea245',
                            '400': '#5db76f',
                            '500': '#8ccc99',
                            '600': '#bbe1c3',
                            '700': '#eaf6ec',
                            foreground: '#fff',
                            DEFAULT: '#247e35',
                        },
                        warning: {
                            '50': '#50360c',
                            '100': '#875b14',
                            '200': '#be801c',
                            '300': '#f5a524',
                            '400': '#f7b955',
                            '500': '#face87',
                            '600': '#fce2b8',
                            '700': '#fef6e9',
                            foreground: '#000',
                            DEFAULT: '#be801c',
                        },
                        danger: {
                            '50': '#4b071f',
                            '100': '#7f0c34',
                            '200': '#b21049',
                            '300': '#e6155e',
                            '400': '#ec4a82',
                            '500': '#f17ea6',
                            '600': '#f7b3cb',
                            '700': '#fde8ef',
                            foreground: '#fff',
                            DEFAULT: '#b21049',
                        },
                        background: '#000000',
                        foreground: {
                            '50': '#535353',
                            '100': '#8c8c8c',
                            '200': '#c6c6c6',
                            '300': '#ffffff',
                            '400': '#ffffff',
                            '500': '#ffffff',
                            '600': '#ffffff',
                            '700': '#ffffff',
                            foreground: '#000',
                            DEFAULT: '#c6c6c6',
                        },
                        content1: {
                            DEFAULT: '#18181b',
                            foreground: '#fff',
                        },
                        content2: {
                            DEFAULT: '#27272a',
                            foreground: '#fff',
                        },
                        content3: {
                            DEFAULT: '#3f3f46',
                            foreground: '#fff',
                        },
                        content4: {
                            DEFAULT: '#52525b',
                            foreground: '#fff',
                        },
                        focus: '#647384',
                        overlay: '#ffffff',
                        divider: '#ffffff',
                    },
                },
            },
            layout: {
                fontSize: {
                    tiny: '1rem',
                    small: '1.125rem',
                    medium: '1.15rem',
                    large: '1.25rem',
                },
                lineHeight: {
                    tiny: '1.5rem',
                    small: '1.75rem',
                    medium: '2rem',
                    large: '2.25rem',
                },
                radius: {
                    small: '0.25rem',
                    medium: '0.5rem',
                    large: '0.75rem',
                },
                borderWidth: {
                    small: '1.5px',
                    medium: '2.5px',
                    large: '3.5px',
                },
                disabledOpacity: '0.5',
                dividerWeight: '1',
                hoverOpacity: '0.9',
            },
        }),
    ],
} satisfies Config
